apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debug
  name: debug
spec:
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven
        name: debug
        command: 
          - '/bin/sh'
        args:
          - '-c'
          - 'sleep infinity'
      securityContext:
        runAsUser: 0
